name: Topic
description: Use this template for tracking new topic ideas.
body:
  - type: textarea
    attributes:
      label: Title
      placeholder: The best Idea Pool Topic ever
    validations:
      required: true
  - type: textarea
    attributes:
      label: About
      description: What is the topic about? (A brief summary of the topic, topics to be covered)
      placeholder: Brief introduction of The best Idea Pool Topic ever
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Notes, link to materials, articles
      placeholder: "https://example.com"
  - type: dropdown
    id: Idea Pool Format
    attributes:
      label: What is the potential artifact of the topic?
      multiple: true
      options:
        - Ambitions
        - Article
        - Demo
        - Expo
        - Minutes
        - Project
        - Webinar